nome = str(input('Digite o seu nome completo: ')).strip()
nomeMaius = nome.upper()
nomeMinus = nome.lower()
nomeSpace = nome.replace(" ", "")
letrasNome = nome.split()
print(f'Analisando o seu nome.... {nome}')
print(f'Maiúsculo: {nomeMaius}')
print(f'Minusculo: {nomeMinus}')
print(f'Quanti dade de Letras: {len(nomeSpace)}')
print(f'Quantidade de letras do primeiro nome: {len(letrasNome[0])}')